### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by MatthD** [andradedev/Subscribe-Form#1]
Hey guy,

First thanks for your plug-in , very nic to use ;)
Some bugs with front-end :

- I have adde component to my partial
- I call the component
- If I do not mofidy in view->default the two "__SELF__" in the inputs i have this alert error ("AJAX handler 'formSubscribe::onAddSubscriber' was not found.")
-If I modify the view "__SELF__"  to "formSubscribe" I have no error but I do not get anything in my subscriber admin but I got a console error ("Error: Invalid handler name. The correct handler name format is: "onEvent". ")

Thanks :)

**Comment by andradedev** [comment]
Hey MatthD,
thanks for use my Subscribe plug-in.

This error appears because the component it's has been added to a partial, seems to be a bug from October CMS

**Comment by MatthD** [comment]
Wow ok , thanks for the info guy !
So I did call it directly in the laout instead of partial ... works perfectly ;)

**Comment by yuli1250** [comment]
Hello Andradedev,
Thanks for your plugin.
I am currently facing issues with using this plugin in IE (in Google chrome, firefox working perfectly), when I click the submit button, nothing happens, there is also no data stored in database, could you help me with this?
Thanks a lot!
